'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.269
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
'-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
'''<summary>
'''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Toolbar16
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Film_Info__Organizer.Toolbar16", GetType(Toolbar16).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    Friend Shared ReadOnly Property _select() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("select", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property _Sub() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Sub", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Abbrechen() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Abbrechen", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property abouttestfio() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("abouttestfio", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property abouttestfio1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("abouttestfio1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property abouttestfio2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("abouttestfio2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property abouttestfio3() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("abouttestfio3", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Add() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Add", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property addfav16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("addfav16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ajaxloader() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ajaxloader", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ajaxloader1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ajaxloader1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ajaxloader2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ajaxloader2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Alert002() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Alert002", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property App030() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("App030", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property App051() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("App051", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property arrow() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("arrow", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property arrow_down() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("arrow_down", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property back() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Blaettern() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Blaettern", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property browser() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("browser", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property check_result() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("check_result", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property checker() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("checker", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property column_not() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("column_not", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property column_ok() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("column_ok", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property column_warn() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("column_warn", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property config() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("config", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Cover_dl_16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Cover_dl_16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Cover_dl2_16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Cover_dl2_16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Cover_dl3_16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Cover_dl3_16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property CP016() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("CP016", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property CP016_24_24() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("CP016_24_24", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property CP049() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("CP049", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property csvformat() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("csvformat", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property darsteller() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("darsteller", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Design_change() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Design_change", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Down() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Down", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Down1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Down1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Download_aktive() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Download_aktive", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property downloading_icontest() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("downloading_icontest", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property downoverlayicon() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("downoverlayicon", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property edit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property exit_dark() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("exit_dark", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property exit_normal() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("exit_normal", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property exiticon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("exiticon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property exp() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("exp", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Export() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Export", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property fan() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("fan", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property fan1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("fan1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Fanart_search_fast() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Fanart_search_fast", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Favoriten() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Favoriten", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property filmreel() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("filmreel", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Fio_filetype() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Fio_filetype", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property flag_new() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("flag_new", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property flag_new_qm() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("flag_new_qm", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property flag_new_qm_s() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("flag_new_qm_s", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property flag_s_new() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("flag_s_new", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property flag_wichtig() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("flag_wichtig", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property folder_clos() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("folder_clos", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property folder_close() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("folder_close", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Folder124() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Folder124", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Folder129() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Folder129", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Folder132() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Folder132", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Folder150() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Folder150", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property folder48() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("folder48", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property forward() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("forward", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property FSK_Logo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("FSK_Logo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property go() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("go", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property google() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("google", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property grad() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("grad", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property gray_48() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("gray_48", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Hilfe() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Hilfe", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property hv16in() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("hv16in", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property hv16out() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("hv16out", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Info() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Info", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property info3() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("info3", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property infobar() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("infobar", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Infopanel_Table_Backgrounds_green() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Infopanel_Table_Backgrounds_green", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Infopanel_Table_Backgrounds_orange() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Infopanel_Table_Backgrounds_orange", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Infopanel_Table_Backgrounds_red() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Infopanel_Table_Backgrounds_red", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property layout() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("layout", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Light_durchsuchen() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Light_durchsuchen", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Light_hinzufuegen() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Light_hinzufuegen", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Light_laden() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Light_laden", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Light_neuladen() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Light_neuladen", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property lightbutton1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("lightbutton1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property lightbutton2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("lightbutton2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property line() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("line", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property line1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("line1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property linevertical() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("linevertical", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Links() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Links", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Links16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Links16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property loading() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("loading", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property loading2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("loading2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property loadingani() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("loadingani", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property loadingani2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("loadingani2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Löschen() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Löschen", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Media001() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Media001", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Media015() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Media015", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property mediainfoicon16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("mediainfoicon16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property mediainfoicon161() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("mediainfoicon161", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property moviemaze() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("moviemaze", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property mybrowser_maximize() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("mybrowser_maximize", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Net003() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Net003", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Net021() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Net021", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Net036() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Net036", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ninimize() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ninimize", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property normal() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("normal", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property normal_aktualisieren_new() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("normal_aktualisieren_new", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property normal_aktualisieren_new1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("normal_aktualisieren_new1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Normal_durchsuchen() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Normal_durchsuchen", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Normal_hinzufuegen() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Normal_hinzufuegen", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Normal_hinzufügen() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Normal_hinzufügen", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Normal_hinzufügen1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Normal_hinzufügen1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Normal_laden() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Normal_laden", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Normal_neuladen() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Normal_neuladen", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Ok() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Ok", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Ok_gray() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Ok_gray", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ordner_ausscheiden() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ordner_ausscheiden", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ordner_copy() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ordner_copy", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Ordner_kopieren() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Ordner_kopieren", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Ordner_loeschen() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Ordner_loeschen", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Ordner_verschieben() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Ordner_verschieben", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Panel_in() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Panel_in", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Panel_in1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Panel_in1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Panel_out() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Panel_out", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Panel_out1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Panel_out1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Papergrp() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Papergrp", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Papergrp_no() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Papergrp_no", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Play() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Play", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property plugins() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("plugins", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property plugins_gray() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("plugins_gray", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property plus1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("plus1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property progress() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("progress", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property pw_file() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("pw_file", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property pw_moviepilot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("pw_moviepilot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property pw_movieposterdb() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("pw_movieposterdb", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property pw_ofdb() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("pw_ofdb", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property pw_tmdb() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("pw_tmdb", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property pw_wiki() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("pw_wiki", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property pw_xRel() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("pw_xRel", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property pw_yt() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("pw_yt", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property qualy_0() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("qualy_0", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property qualy_1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("qualy_1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property qualy_3() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("qualy_3", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property questionmark() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("questionmark", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property rate_new1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("rate_new1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property rate_new1s() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("rate_new1s", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property rate_new2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("rate_new2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property rate_new2s() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("rate_new2s", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property rate_new3() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("rate_new3", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property rate_new3s() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("rate_new3s", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property refrechdb() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("refrechdb", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property refrechdb1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("refrechdb1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Save() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Save_Filme() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Save_Filme", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Save_mymovies() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Save_mymovies", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property save_windows() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("save_windows", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Save_xbmc() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Save_xbmc", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property search_exact() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("search_exact", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property search_exact1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("search_exact1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property search_schnell() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("search_schnell", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property search_schnell1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("search_schnell1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property securegray() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("securegray", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property securenormal() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("securenormal", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property select_o() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("select_o", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Settings() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Settings", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Settingsbigsym() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Settingsbigsym", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property shield() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("shield", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property sidebarin_16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("sidebarin_16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property sidebarout_16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("sidebarout_16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property sidebarout_161() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("sidebarout_161", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property sidebarout_24() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("sidebarout_24", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property sidebarout_32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("sidebarout_32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Sign006() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Sign006", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Sign007() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Sign007", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Sign0071() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Sign0071", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Sign008() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Sign008", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Sign010() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Sign010", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Sign015() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Sign015", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Sign016() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Sign016", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Speichern() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Speichern", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Speichern1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Speichern1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property st_pinned() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("st_pinned", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property st_unpinned() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("st_unpinned", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property status1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("status1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property status3() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("status3", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property status5() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("status5", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_16_check() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_16_check", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_16_cover() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_16_cover", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_16_cover_test() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_16_cover_test", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_16_fanart() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_16_fanart", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_16_info() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_16_info", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_16_mediainfo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_16_mediainfo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_16_not() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_16_not", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_16_trailer() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_16_trailer", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_16_warn() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_16_warn", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_32_info() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_32_info", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_check() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_check", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_cover() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_cover", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_cover_test() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_cover_test", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_mediainfo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_mediainfo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_not() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_not", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_test() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_test", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_trailer() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_trailer", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property staty_warn() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("staty_warn", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property subfav16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("subfav16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Suche() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Suche", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Suche_datenbank() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Suche_datenbank", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property suchen_close() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("suchen_close", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property suchen_close_hover() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("suchen_close_hover", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property suchen_normal() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("suchen_normal", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property testdia() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("testdia", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property testdia1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("testdia1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property toolbar32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("toolbar32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property trailer_fast() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("trailer_fast", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property tree_default() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("tree_default", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Tree_in() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Tree_in", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Tree_out() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Tree_out", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Unbenannt() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Unbenannt", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Unbenannt1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Unbenannt1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Unbenannt2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Unbenannt2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Unbenanntsasfgdsfrg() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Unbenanntsasfgdsfrg", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property undo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("undo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Up() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Up", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Update() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Update", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property View_details() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("View_details", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property View_extragroß() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("View_extragroß", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property View_groß() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("View_groß", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property View_inhalt() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("View_inhalt", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property View_kacheln() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("View_kacheln", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property View_klein() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("View_klein", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property View_liste() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("View_liste", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property View_mittel() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("View_mittel", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property warning() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property warning1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("warning1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property warning2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("warning2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property warning3() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("warning3", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property warning4() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("warning4", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property watched_no() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("watched_no", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property watched_yes() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("watched_yes", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Web() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Web", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property write() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("write", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Write001() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Write001", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property xbmc1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("xbmc1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
