'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.1
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Film_Info__Organizer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Abbrechen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Abbrechen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ajax_loader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajax-loader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ajax_loader1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajax-loader1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property App030() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("App030", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property infobar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("infobar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Infopanel_Table_Backgrounds_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Infopanel_Table_Backgrounds_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Infopanel_Table_Backgrounds_orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Infopanel_Table_Backgrounds_orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Infopanel_Table_Backgrounds_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Infopanel_Table_Backgrounds_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property line() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("line", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property line1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("line1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property linevertical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("linevertical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menubacktest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menubacktest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menubacktest2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menubacktest2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property no_cover_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_cover_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Settingsbigsym() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settingsbigsym", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Settingsbigsym2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settingsbigsym2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Speichern() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Speichern", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property testdia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("testdia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property testdia1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("testdia1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property token() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("token", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xxt1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xxt1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
