'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.269
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Film_Info__Organizer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property ajaxloader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajaxloader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ajaxloaderbig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajaxloaderbig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property App029() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("App029", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property App030() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("App030", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property but_fulls_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("but_fulls_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property but_fulls_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("but_fulls_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property but_nofulls_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("but_nofulls_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property but_nofulls_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("but_nofulls_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property c102() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c102", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;Filter&gt;
        '''  &lt;cFilter&gt;[ _.-]+\(?\d{4}\)?.*&lt;/cFilter&gt;
        '''  &lt;cFilter&gt;[ _.-]+blu[ _.-]?ray.*&lt;/cFilter&gt;
        '''  &lt;cFilter&gt;[ _.-]+bd[ _.-]?rip.*&lt;/cFilter&gt;
        '''  &lt;cFilter&gt;[ _.-]+dvd.*&lt;/cFilter&gt;
        '''  &lt;cFilter&gt;[ _.-]+(HD)?720.*&lt;/cFilter&gt;
        '''  &lt;cFilter&gt;[ _.-]+(HD)?1080.*&lt;/cFilter&gt;
        '''  &lt;cFilter&gt;[ _.-]+ac3.*&lt;/cFilter&gt;
        '''  &lt;cFilter&gt;[ _.-]+dts.*&lt;/cFilter&gt;
        '''  &lt;cFilter&gt;[ _.-]+divx.*&lt;/cFilter&gt;
        '''  &lt;cFilter&gt;[ _.-]+xvid.*&lt;/cFilter&gt;
        '''  &lt;cFilter&gt;[ _.-]+dc[ _.-]?.*&lt;/cFilter&gt;
        '''  &lt;cFilter&gt;[ _.-]+dir(ector&apos;?s [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property CostumFilter() As String
            Get
                Return ResourceManager.GetString("CostumFilter", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Downloadboxbig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Downloadboxbig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property downloading_icontest2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("downloading_icontest2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Export() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Export", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property flag_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flag_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flag_s_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_s_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flag_s_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_s_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flags_qm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flags_qm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flags_s_qm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flags_s_qm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imageres143() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres143", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imageres192() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres192", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property indicator_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("indicator_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property indicator_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("indicator_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property infobar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("infobar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Infopanel_Table_Backgrounds_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Infopanel_Table_Backgrounds_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Infopanel_Table_Backgrounds_orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Infopanel_Table_Backgrounds_orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Infopanel_Table_Backgrounds_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Infopanel_Table_Backgrounds_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Interop_Shell32() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Interop_Shell32", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property kontextmenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kontextmenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Light_Beer_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Light-Beer-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property line() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("line", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property line1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("line1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property linevertical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("linevertical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Misc_Mail_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Misc-Mail-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property no_cover_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_cover_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property oVideo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oVideo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property qu_hd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("qu_hd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property qu_hq() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("qu_hq", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property qu_sd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("qu_sd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        '''&lt;Genres&gt;
        '''    &lt;Genre&gt;
        '''        &lt;id&gt;28&lt;/id&gt;
        '''        &lt;Name-DE&gt;Action&lt;/Name-DE&gt;
        '''        &lt;Name-EN&gt;Action&lt;/Name-EN&gt;
        '''        &lt;Filter /&gt;
        '''    &lt;/Genre&gt;
        '''    &lt;Genre&gt;
        '''        &lt;id&gt;12&lt;/id&gt;
        '''        &lt;Name-DE&gt;Abenteuer&lt;/Name-DE&gt;
        '''        &lt;Name-EN&gt;Adventure&lt;/Name-EN&gt;
        '''        &lt;Filter /&gt;
        '''    &lt;/Genre&gt;
        '''    &lt;Genre&gt;
        '''        &lt;id&gt;16&lt;/id&gt;
        '''        &lt;Name-DE&gt;Animation&lt;/Name-DE&gt;
        '''        &lt;Name-EN&gt;Animation&lt;/Name-EN&gt;
        '''        &lt;Filter /&gt;
        '''    &lt;/Genre&gt;
        '''    &lt;Genre&gt;
        '''        &lt;id&gt;35&lt;/ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property setGenre() As String
            Get
                Return ResourceManager.GetString("setGenre", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Settingsbigsym() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settingsbigsym", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shadow_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shadow_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shadow_gray_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shadow_gray_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shadow_gray_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shadow_gray_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shadow_gray_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shadow_gray_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property test_eye_unwatched() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("test_eye_unwatched", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property test_eye_watched() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("test_eye_watched", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property test_eye_watched1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("test_eye_watched1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property test_eye_watched2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("test_eye_watched2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property threepixline_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("threepixline_l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolstrip_checked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolstrip_checked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolstrip_radio_checked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolstrip_radio_checked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Video_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Video_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Wizard1256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wizard1256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Wizard64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wizard64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
